import * as personal from './personal.js';
import * as store from '../js/store.js';
import { dateKey } from '../js/body.js';
import { parseNumber } from '../js/units.js';
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let ui;
export function wirePersonal(callbacks){ui=callbacks;}
const btn=(id,label,cls='secondary')=>`<button class="${cls}" data-action="personal-${id}">${label}</button>`;
export function profileSettings(){const p=personal.profile;return `<section class="settings-block personal-block"><span class="eyebrow">YOUR LIVING PROFILE</span><h2>${p?.name?esc(p.name)+', in context.':'A coach that knows you.'}</h2><p class="small">${p?esc(p.priority):'Bring your training split, priorities and coaching preferences into FORM. Personal information is kept on this device and sent to Gemini only when you ask the Coach.'}</p>${p?.routines.length?`<p class="small muted">${p.routines.length} personal sessions · working weights supplied by you · unconfirmed reps stay open.</p>`:''}${p?.unknowns.length?`<details class="small"><summary>Still to confirm (${p.unknowns.length})</summary><ul>${p.unknowns.map(x=>`<li>${esc(x)}</li>`).join('')}</ul></details>`:''}<div class="dialog-actions">${btn('import',p?'Import updated profile':'Import training profile','primary')}${btn('notes','Edit coaching notes')}</div><div class="dialog-actions">${p?btn('export','Export profile + check-ins'):''}</div><p class="small muted">Use your private FORM training-profile JSON. Import adds or updates matching routines; it keeps existing workout history. Profile exports are separate from workout backups.</p><input id="personal-file" type="file" accept="application/json" hidden></section>`;}
export function journalCheckin(){const trend=personal.weightTrend(store.state.bodyweight),last=personal.checkins.at(-1);return `<section class="week-card recovery-card"><div class="week-title"><h3>The person behind the performance.</h3><span>${last?'Last check-in '+esc(last.date):'NO CHECK-INS YET'}</span></div><div class="session-summary"><div><span class="eyebrow">7-DAY AVERAGE</span><strong>${trend.average==null?'—':trend.average.toFixed(1)} <small>kg · ${trend.count} entries</small></strong></div><div><span class="eyebrow">VS PREVIOUS 7 DAYS</span><strong>${trend.change==null?'—':(trend.change>0?'+':'')+trend.change.toFixed(1)} <small>${trend.change==null?'more entries needed':'kg'}</small></strong></div></div><p class="small muted" style="font-family:var(--sans);font-size:12px">Weight trends, food, sleep and wrestling belong in the same conversation. No invented calorie target.</p><div class="dialog-actions">${btn('checkin','Log a check-in ↗','primary')}${btn('review','Ask Coach to review')}</div></section>`;}
export async function importPersonalFile(file){if(!file||file.size>250000)throw Error('Invalid profile file');const p=JSON.parse(await file.text());if(!personal.validateProfile(p)||p.checkins&&(!Array.isArray(p.checkins)||p.checkins.length>730||!p.checkins.every(personal.validateCheckin)))throw Error('Invalid profile');ui.dialog('Make this your training profile?',`<p class="small">${esc(p.name)} · ${esc(p.priority)}</p><p class="small muted">${p.routines.length} routines will be added or updated. Previous workouts remain intact. Unknown reps and exercises stay unconfirmed.</p><div class="dialog-actions">${btn('confirm-import','Use this profile','primary')}</div>`,root=>{root.querySelector('[data-action=personal-confirm-import]').onclick=async e=>{e.currentTarget.disabled=true;try{await store.flush();await personal.importProfile(p,store.state.catalog);await store.init();ui.close();ui.refresh();ui.notify('Your profile and training split are ready.');}catch{e.currentTarget.disabled=false;ui.notify('Profile could not be saved. Please try again.');}};});}
export async function personalAction(action){const a=action.replace('personal-','');if(a==='import'){document.querySelector('#personal-file').click();return;}if(a==='review'){ui.ask('Review my fat-loss progress, strength, recovery, hunger, food intake and wrestling together. Use trends from my actual records, say what is missing, and follow my coaching notes.');return;}
 if(a==='export'){const p={...personal.profile,checkins:personal.checkins},url=URL.createObjectURL(new Blob([JSON.stringify(p,null,2)],{type:'application/json'})),link=document.createElement('a');link.href=url;link.download='FORM-private-training-profile.json';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);return;}
 if(a==='notes'){ui.dialog('What your coach should know.',`<form id="personal-notes"><label class="field">Current priorities, preferences and changes<textarea rows="12" maxlength="12000">${esc(personal.profile?.notes||'')}</textarea></label><p class="small muted">Update these when your circumstances change. These notes are included in every Coach request.</p><button class="primary" type="submit">Save coaching notes</button></form>`,root=>{root.querySelector('form').onsubmit=async e=>{e.preventDefault();try{await personal.saveNotes(root.querySelector('textarea').value);ui.close();ui.refresh();ui.notify('Coaching notes saved.');}catch{ui.notify('Notes could not be saved.');}};});return;}
 if(a==='checkin'){
 const today=dateKey(),existing=personal.checkins.find(c=>c.date===today)||{},fields=[['weightKg','Bodyweight / kg',20,400],['kcal','Whole-day calories / kcal',0,20000],['protein','Whole-day protein / g',0,1000],['carbs','Whole-day carbohydrates / g',0,2000],['fat','Whole-day fat / g',0,1000],['sleep','Sleep / hours',0,24],['energy','Energy / 1 low – 5 high',1,5],['hunger','Hunger / 1 low – 5 high',1,5],['wrestlingMinutes','Wrestling / minutes',0,600],['wrestlingEffort','Wrestling effort / 1 easy – 10 maximal',1,10]];
 ui.dialog('Check in with yourself.',`<form id="personal-checkin"><label class="field">Date<input type="date" name="date" value="${today}" max="${today}" required></label><p class="small muted">Fill in what you know. Leave the rest blank. Intake is your whole-day total, not a prescribed target.</p><div class="checkin-fields">${fields.map(([k,l,min,max])=>`<label class="field">${l}<input name="${k}" inputmode="decimal" type="number" step="any" min="${min}" max="${max}" value="${existing[k]??''}"></label>`).join('')}</div><label class="field">Meals, soreness, performance, or anything worth noting<textarea name="note" maxlength="2000" rows="3">${esc(existing.note||'')}</textarea></label><p id="checkin-error" class="small" role="alert"></p><button class="primary" type="submit">Save check-in ↗</button></form>`,root=>{const f=root.querySelector('form');f.elements.date.onchange=()=>{const c=personal.checkins.find(c=>c.date===f.elements.date.value)||{};for(const [k]of fields)f.elements[k].value=c[k]??'';f.elements.note.value=c.note||'';};f.onsubmit=async e=>{e.preventDefault();const c={date:f.elements.date.value,note:f.elements.note.value};for(const [k]of fields)c[k]=f.elements[k].value===''?null:parseNumber(f.elements[k].value);if(!personal.validateCheckin(c)||c.date>today){root.querySelector('#checkin-error').textContent='Check the date and values.';return;}try{await store.flush();await personal.saveCheckin(c);await store.init();ui.close();ui.refresh();ui.notify('Check-in saved. Coach has the full picture.');}catch{root.querySelector('#checkin-error').textContent='Could not save. Keep this open and try again.';}};});
 }
}
